import re
import torch
from transformers import *
import spacy
import numpy as np
import pandas as pd
from sklearn.metrics import f1_score, accuracy_score, confusion_matrix, ConfusionMatrixDisplay, classification_report
nlp = spacy.load("pl_core_news_lg")

EMOJI_TO_POLISH = {
'©': 'znak_praw_autorskich',
 '®': 'znak_zastrzeżony',
 '‼': 'podwójny_wykrzyknik',
 '⁉': 'wykrzyknik_z_pytajnikiem',
 '™': 'znak_towarowy',
 'ℹ': 'informacja',
 '↗': 'strzałka_w_górę_w_prawo',
 '↘': 'strzałka_w_dół_w_prawo',
 '⌚': 'zegarek',
 '⌛': 'klepsydra',
 '⏩': 'przewiń_do_przodu',
 '⏬': 'podwójna_strzałka_w_dół',
 '⏰': 'budzik',
 '⏱': 'stoper',
 '⏳': 'klepsydra_z_płynącym_piaskiem',
 '▪': 'mały_czarny_kwadrat',
 '▫': 'mały_biały_kwadrat',
 '▶': 'przycisk_odtwarzania',
 '◼': 'średni_czarny_kwadrat',
 '◾': 'czarny_kwadrat',
 '☀': 'słońce',
 '☁': 'chmura',
 '☃': 'bałwan',
 '☄': 'kometa',
 '☎': 'telefon',
 '☑': 'zaznaczone_pole_wyboru',
 '☔': 'parasol_z_kroplami_deszczu',
 '☕': 'gorący_napój',
 '☘': 'koniczyna',
 '☝': 'palec_wskazujący_w_górę',
 '☠': 'czaszka_i_skrzyżowane_kości',
 '☹': 'smutna_twarz',
 '☺': 'uśmiechnięta_twarz',
 '♀': 'symbol_kobiety',
 '♂': 'symbol_mężczyzny',
 '♟': 'pionek_szachowy',
 '♥': 'serce',
 '♦': 'karo',
 '♻': 'symbol_recyklingu',
 '⚔': 'skrzyżowane_miecze',
 '⚖': 'waga',
 '⚗': 'alembik',
 '⚙': 'koło_zębate',
 '⚠': 'znak_ostrzegawczy',
 '⚡': 'wysokie_napięcie',
 '⚪': 'białe_koło',
 '⚫': 'czarne_koło',
 '⚰': 'trumna',
 '⚽': 'piłka_nożna',
 '⛏': 'kilof',
 '⛔': 'zakaz_wjazdu',
 '⛷': 'narciarz',
 '⛹': 'osoba_z_piłką',
 '⛽': 'dystrybutor_paliwa',
 '✅': 'biały_znacznik_wyboru',
 '✈': 'samolot',
 '✉': 'koperta',
 '✊': 'uniesiona_pięść',
 '✋': 'uniesiona_dłoń',
 '✌': 'gest_zwycięstwa',
 '✍': 'pisząca_dłoń',
 '✏': 'ołówek',
 '✔': 'znacznik_wyboru',
 '✡': 'gwiazda_dawida',
 '✨': 'iskierki',
 '❄': 'płatek_śniegu',
 '❌': 'krzyżyk',
 '❎': 'przycisk_krzyżyka',
 '❓': 'znak_zapytania',
 '❔': 'biały_znak_zapytania',
 '❕': 'biały_wykrzyknik',
 '❗': 'wykrzyknik',
 '❣': 'wykrzyknik_w_kształcie_serca',
 '❤': 'czerwone_serce',
 '➕': 'plus',
 '➖': 'minus',
 '➡': 'strzałka_w_prawo',
 '⤴': 'strzałka_w_prawo_zakręcająca_w_górę',
 '⤵': 'strzałka_w_prawo_zakręcająca_w_dół',
 '⬅': 'strzałka_w_lewo',
 '⬆': 'strzałka_w_górę',
 '⬇': 'strzałka_w_dół',
 '⬛': 'duży_czarny_kwadrat',
 '⬜': 'duży_biały_kwadrat',
 '⭐': 'gwiazda',
 '🅰': 'grupa_krwi_A',
 '🆕': 'nowy',
 '🆘': 'SOS',
 '🆙': 'w_górę',
 '🆚': 'kontra',
 '🈵': 'przycisk_"pełny"_po_japońsku',
 '🌀': 'cyklon',
 '🌇': 'zachód_słońca',
 '🌈': 'tęcza',
 '🌊': 'fala',
 '🌌': 'droga_mleczna',
 '🌍': 'glob_pokazujący_Europę_i_Afrykę',
 '🌎': 'glob_pokazujący_Amerykę',
 '🌐': 'glob_z_południkami',
 '🌕': 'pełnia_księżyca',
 '🌙': 'półksiężyc',
 '🌚': 'nów_z_twarzą',
 '🌛': 'pierwsza_kwadra_z_twarzą',
 '🌝': 'pełnia_z_twarzą',
 '🌞': 'słońce_z_twarzą',
 '🌟': 'świecąca_gwiazda',
 '🌠': 'spadająca_gwiazda',
 '🌦': 'słońce_za_chmurą_z_deszczem',
 '🌧': 'chmura_z_deszczem',
 '🌨': 'chmura_ze_śniegiem',
 '🌫': 'mgła',
 '🌬': 'wiejąca_twarz',
 '🌭': 'hot_dog',
 '🌱': 'sadzonka',
 '🌲': 'wiecznie_zielone_drzewo',
 '🌳': 'drzewo_liściaste',
 '🌴': 'palma',
 '🌶': 'papryka_chili',
 '🌷': 'tulipan',
 '🌸': 'kwiat_wiśni',
 '🌹': 'róża',
 '🌻': 'słonecznik',
 '🌼': 'kwiat',
 '🌽': 'kolba_kukurydzy',
 '🌾': 'kłos_ryżu',
 '🌿': 'zioło',
 '🍀': 'czterolistna_koniczyna',
 '🍁': 'liść_klonu',
 '🍂': 'opadły_liść',
 '🍃': 'liść_na_wietrze',
 '🍄': 'grzyb',
 '🍅': 'pomidor',
 '🍇': 'winogrona',
 '🍈': 'melon',
 '🍉': 'arbuz',
 '🍊': 'mandarynka',
 '🍋': 'cytryna',
 '🍌': 'banan',
 '🍍': 'ananas',
 '🍎': 'czerwone_jabłko',
 '🍏': 'zielone_jabłko',
 '🍐': 'gruszka',
 '🍑': 'brzoskwinia',
 '🍒': 'wiśnie',
 '🍓': 'truskawka',
 '🍔': 'hamburger',
 '🍕': 'pizza',
 '🍖': 'mięso_na_kości',
 '🍗': 'udko_z_kurczaka',
 '🍘': 'krakers_ryżowy',
 '🍙': 'kulka_ryżowa',
 '🍚': 'gotowany_ryż',
 '🍛': 'ryż_curry',
 '🍜': 'parująca_miska',
 '🍝': 'spaghetti',
 '🍞': 'chleb',
 '🍟': 'frytki',
 '🍠': 'pieczony_batat',
 '🍡': 'dango',
 '🍢': 'oden',
 '🍣': 'sushi',
 '🍤': 'smażona_krewetka',
 '🍥': 'ciastko_rybne_z_spiralnym_wzorem',
 '🍦': 'lody_włoskie',
 '🍧': 'lody_hawajskie',
 '🍨': 'lody',
 '🍩': 'pączek',
 '🍪': 'ciastko',
 '🍫': 'tabliczka_czekolady',
 '🍬': 'cukierek',
 '🍭': 'lizak',
 '🍮': 'krem_karmelowy',
 '🍯': 'garnek_miodu',
 '🍰': 'kawałek_ciasta',
 '🍱': 'pudełko_bento',
 '🍲': 'garnek_z_jedzeniem',
 '🍳': 'gotowanie',
 '🍴': 'widelec_i_nóż',
 '🍵': 'filiżanka_bez_ucha',
 '🍶': 'sake',
 '🍷': 'kieliszek_wina',
 '🍸': 'kieliszek_koktajlowy',
 '🍹': 'drink_tropikalny',
 '🍺': 'kufel_piwa',
 '🍻': 'stukające_się_kufle_piwa',
 '🍼': 'butelka_dla_niemowląt',
 '🍽': 'widelec_i_nóż_z_talerzem',
 '🍾': 'butelka_z_wyskakującym_korkiem',
 '🍿': 'popcorn',
 '🎀': 'kokarda',
 '🎁': 'zapakowany_prezent',
 '🎂': 'tort_urodzinowy',
 '🎃': 'dynia_halloween',
 '🎄': 'choinka',
 '🎅': 'święty_mikołaj',
 '🎆': 'fajerwerki',
 '🎇': 'zimne_ognie',
 '🎈': 'balon',
 '🎉': 'petarda_konfetti',
 '🎊': 'kula_konfetti',
 '🎋': 'drzewo_tanabata',
 '🎌': 'skrzyżowane_flagi',
 '🎍': 'dekoracja_sosnowa',
 '🎎': 'lalki_japońskie',
 '🎏': 'karp_wiatrowy',
 '🎐': 'dzwonek_wiatrowy',
 '🎑': 'ceremonia_oglądania_księżyca',
 '🎒': 'plecak_szkolny',
 '🎓': 'czapka_absolwenta',
 '🎖': 'medal_wojskowy',
 '🎗': 'wstążka_przypomnienia',
 '🎙': 'mikrofon_studyjny',
 '🎚': 'suwak_poziomu',
 '🎛': 'pokrętła_kontrolne',
 '🎞': 'klatki_filmowe',
 '🎟': 'bilety_wstępu',
 '🎠': 'koń_z_karuzeli',
 '🎡': 'diabelski_młyn',
 '🎢': 'kolejka_górska',
 '🎣': 'wędka',
 '🎤': 'mikrofon',
 '🎥': 'kamera_filmowa',
 '🎦': 'kino',
 '🎧': 'słuchawki',
 '🎨': 'paleta_malarska',
 '🎩': 'cylinder',
 '🎪': 'namiot_cyrkowy',
 '🎫': 'bilet',
 '🎬': 'klaps_filmowy',
 '🎭': 'maski_teatralne',
 '🎮': 'kontroler_gry',
 '🎯': 'strzał_w_dziesiątkę',
 '🎰': 'automat_do_gry',
 '🎱': 'bila_8',
 '🎲': 'kostka_do_gry',
 '🎳': 'kręgle',
 '🎴': 'karty_do_gry_hanafuda',
 '🎵': 'nuta_muzyczna',
 '🎶': 'nuty_muzyczne',
 '🎷': 'saksofon',
 '🎸': 'gitara',
 '🎹': 'klawiatura_muzyczna',
 '🎺': 'trąbka',
 '🎻': 'skrzypce',
 '🎼': 'partytura_muzyczna',
 '🎽': 'koszulka_do_biegania',
 '🎾': 'tenis',
 '🎿': 'narty',
 '🏀': 'koszykówka',
 '🏁': 'flaga_w_szachownicę',
 '🏂': 'snowboardzista',
 '🏃': 'biegacz',
 '🏄': 'surfer',
 '🏅': 'medal_sportowy',
 '🏆': 'puchar',
 '🏈': 'futbol_amerykański',
 '🏉': 'piłka_do_rugby',
 '🏊': 'pływak',
 '🏋': 'podnoszenie_ciężarów',
 '🏌': 'golfista',
 '🏍': 'motocykl',
 '🏎': 'samochód_wyścigowy',
 '🏐': 'siatkówka',
 '🏑': 'hokej_na_trawie',
 '🏒': 'hokej_na_lodzie',
 '🏓': 'tenis_stołowy',
 '🏔': 'góra_ze_śnieżnym_szczytem',
 '🏕': 'kemping',
 '🏖': 'plaża_z_parasolem',
 '🏗': 'budowa',
 '🏘': 'domy',
 '🏙': 'pejzaż_miejski',
 '🏚': 'opuszczony_dom',
 '🏛': 'budynek_klasyczny',
 '🏜': 'pustynia',
 '🏝': 'wyspa_bezludna',
 '🏞': 'park_narodowy',
 '🏟': 'stadion',
 '🏠': 'dom',
 '🏡': 'dom_z_ogrodem',
 '🏢': 'biurowiec',
 '🏣': 'poczta_japońska',
 '🏤': 'poczta',
 '🏥': 'szpital',
 '🏦': 'bank',
 '🏧': 'bankomat',
 '🏨': 'hotel',
 '🏩': 'hotel_miłości',
 '🏪': 'sklep_całodobowy',
 '🏫': 'szkoła',
 '🏬': 'dom_towarowy',
 '🏭': 'fabryka',
 '🏮': 'czerwony_lampion',
 '🏯': 'zamek_japoński',
 '🏰': 'zamek_europejski',
 '🏳': 'biała_flaga',
 '🏴': 'czarna_flaga',
 '🏵': 'rozeta',
 '🏷': 'etykieta',
 '🏸': 'badminton',
 '🏹': 'łuk_i_strzała',
 '🏺': 'amfora',
 '🏻': 'jasny_odcień_skóry',
 '🏼': 'średnio_jasny_odcień_skóry',
 '🏽': 'średni_odcień_skóry',
 '🏾': 'średnio_ciemny_odcień_skóry',
 '🏿': 'ciemny_odcień_skóry',
 '🐀': 'szczur',
 '🐁': 'mysz',
 '🐂': 'wół',
 '🐃': 'bawół_wodny',
 '🐄': 'krowa',
 '🐅': 'tygrys',
 '🐆': 'leopard',
 '🐇': 'królik',
 '🐈': 'kot',
 '🐉': 'smok',
 '🐊': 'krokodyl',
 '🐋': 'wieloryb',
 '🐌': 'ślimak',
 '🐍': 'wąż',
 '🐎': 'koń',
 '🐏': 'baran',
 '🐐': 'koza',
 '🐑': 'owca',
 '🐒': 'małpa',
 '🐓': 'kogut',
 '🐔': 'kura',
 '🐕': 'pies',
 '🐖': 'świnia',
 '🐗': 'dzik',
 '🐘': 'słoń',
 '🐙': 'ośmiornica',
 '🐚': 'muszla',
 '🐛': 'robak',
 '🐜': 'mrówka',
 '🐝': 'pszczoła',
 '🐞': 'biedronka',
 '🐟': 'ryba',
 '🐠': 'ryba_tropikalna',
 '🐡': 'ryba_rozdymka',
 '🐢': 'żółw',
 '🐣': 'wykluwające_się_kurczę',
 '🐤': 'kurczątko',
 '🐥': 'kurczątko_z_przodu',
 '🐦': 'ptak',
 '🐧': 'pingwin',
 '🐨': 'koala',
 '🐩': 'pudel',
 '🐪': 'wielbłąd',
 '🐫': 'wielbłąd_dwugarbny',
 '🐬': 'delfin',
 '🐭': 'mysz',
 '🐮': 'krowa',
 '🐯': 'tygrys',
 '🐰': 'królik',
 '🐱': 'kot',
 '🐲': 'smok',
 '🐳': 'wieloryb_tryskający_wodą',
 '🐴': 'koń',
 '🐵': 'małpia_twarz',
 '🐶': 'psia_twarz',
 '🐷': 'świńska_twarz',
 '🐸': 'żaba',
 '🐹': 'chomik',
 '🐺': 'wilk',
 '🐻': 'niedźwiedź',
 '🐼': 'panda',
 '🐽': 'świński_ryj',
 '🐾': 'ślady_łap',
 '👀': 'oczy',
 '👁': 'oko',
 '👂': 'ucho',
 '👃': 'nos',
 '👄': 'usta',
 '👅': 'język',
 '👆': 'palec_wskazujący_w_górę',
 '👇': 'palec_wskazujący_w_dół',
 '👈': 'palec_wskazujący_w_lewo',
 '👉': 'palec_wskazujący_w_prawo',
 '👊': 'pięść',
 '👋': 'machająca_dłoń',
 '👌': 'ok',
 '👍': 'kciuk_w_górę',
 '👎': 'kciuk_w_dół',
 '👏': 'oklaski',
 '👐': 'otwarte_dłonie',
 '👑': 'korona',
 '👒': 'kapelusz_damski',
 '👓': 'okulary',
 '👔': 'krawat',
 '👕': 'koszulka',
 '👖': 'dżinsy',
 '👗': 'sukienka',
 '👘': 'kimono',
 '👙': 'bikini',
 '👚': 'ubrania_damskie',
 '👛': 'portmonetka',
 '👜': 'torebka',
 '👝': 'saszetka',
 '👞': 'but_męski',
 '👟': 'but_sportowy',
 '👠': 'but_na_wysokim_obcasie',
 '👡': 'sandał_damski',
 '👢': 'kozak_damski',
 '👣': 'ślady_stóp',
 '👤': 'popiersie',
 '👥': 'popiersia',
 '👦': 'chłopiec',
 '👧': 'dziewczynka',
 '👨': 'mężczyzna',
 '👩': 'kobieta',
 '👪': 'rodzina',
 '👫': 'mężczyzna_i_kobieta_trzymający_się_za_ręce',
 '👬': 'dwóch_mężczyzn_trzymających_się_za_ręce',
 '👭': 'dwie_kobiety_trzymające_się_za_ręce',
 '👮': 'policjant',
 '👯': 'tancerki',
 '👰': 'panna_młoda_z_welonem',
 '👱': 'osoba_blond',
 '👲': 'mężczyzna_w_chińskiej_czapce',
 '👳': 'mężczyzna_w_turbanie',
 '👴': 'starszy_mężczyzna',
 '👵': 'starsza_kobieta',
 '👶': 'niemowlę',
 '👷': 'pracownik_budowlany',
 '👸': 'księżniczka',
 '👹': 'ogr',
 '👺': 'goblin',
 '👻': 'duch',
 '👼': 'aniołek',
 '👽': 'kosmita',
 '👾': 'potwór_kosmiczny',
 '👿': 'diabełek',
 '💀': 'czaszka',
 '💁': 'osoba_przy_biurku_informacji',
 '💂': 'strażnik',
 '💃': 'tancerka',
 '💄': 'szminka',
 '💅': 'lakier_do_paznokci',
 '💆': 'masaż_twarzy',
 '💇': 'strzyżenie',
 '💈': 'słup_fryzjerski',
 '💉': 'strzykawka',
 '💊': 'pigułka',
 '💋': 'ślad_pocałunku',
 '💌': 'list_miłosny',
 '💍': 'pierścionek',
 '💎': 'klejnot',
 '💏': 'pocałunek',
 '💐': 'bukiet',
 '💑': 'para_z_sercem',
 '💒': 'ślub',
 '💓': 'bijące_serce',
 '💔': 'złamane_serce',
 '💕': 'dwa_serca',
 '💖': 'iskrzące_serce',
 '💗': 'rosnące_serce',
 '💘': 'serce_ze_strzałą',
 '💙': 'niebieskie_serce',
 '💚': 'zielone_serce',
 '💛': 'żółte_serce',
 '💜': 'fioletowe_serce',
 '💝': 'serce_z_kokardą',
 '💞': 'obracające_się_serca',
 '💟': 'dekoracja_serca',
 '💠': 'romb_z_kropką',
 '💡': 'żarówka',
 '💢': 'symbol_złości',
 '💣': 'bomba',
 '💤': 'symbol_snu',
 '💥': 'kolizja',
 '💦': 'krople',
 '💧': 'kropla',
 '💨': 'pędzący',
 '💩': 'kupa',
 '💪': 'napięty_biceps',
 '💫': 'zawroty_głowy',
 '💬': 'dymek_mowy',
 '💭': 'dymek_myśli',
 '💮': 'biały_kwiat',
 '💯': 'sto_punktów',
 '💰': 'worek_pieniędzy',
 '💱': 'wymiana_walut',
 '💲': 'znak_dolara',
 '💳': 'karta_kredytowa',
 '💴': 'banknot',
 '💵': 'banknot',
 '💶': 'banknot',
 '💷': 'banknot',
 '💸': 'pieniądze_ze_skrzydłami',
 '💹': 'rosnący_wykres',
 '💺': 'fotel',
 '💻': 'laptop',
 '💼': 'teczka',
 '💽': 'minidysk',
 '💾': 'dyskietka',
 '💿': 'płyta_optyczna',
 '📀': 'dvd',
 '📁': 'folder_plików',
 '📂': 'otwarty_folder',
 '📃': 'strona',
 '📄': 'strona',
 '📅': 'kalendarz',
 '📆': 'kalendarz',
 '📇': 'kartoteka',
 '📈': 'rosnący_wykres',
 '📉': 'malejący_wykres',
 '📊': 'wykres_słupkowy',
 '📋': 'schowek',
 '📌': 'pinezka',
 '📍': 'okrągła_pinezka',
 '📎': 'spinacz',
 '📏': 'linijka',
 '📐': 'ekierka',
 '📑': 'zakładki',
 '📒': 'notes',
 '📓': 'notatnik',
 '📔': 'notatnik',
 '📕': 'zamknięta_książka',
 '📖': 'otwarta_książka',
 '📗': 'zielona_książka',
 '📘': 'niebieska_książka',
 '📙': 'pomarańczowa_książka',
 '📚': 'książki',
 '📛': 'plakietka_z_nazwiskiem',
 '📜': 'zwój',
 '📝': 'notatka',
 '📞': 'słuchawka_telefoniczna',
 '📟': 'pager',
 '📠': 'faks',
 '📡': 'antena_satelitarna',
 '📢': 'głośnik',
 '📣': 'megafon',
 '📤': 'tacka_na_dokumenty',
 '📥': 'tacka_na_dokumenty',
 '📦': 'paczka',
 '📧': 'e-mail',
 '📨': 'przychodząca_koperta',
 '📩': 'koperta_ze_strzałką',
 '📪': 'zamknięta_skrzynka',
 '📫': 'zamknięta_skrzynka',
 '📬': 'otwarta_skrzynka',
 '📭': 'otwarta_skrzynka',
 '📮': 'skrzynka_pocztowa',
 '📯': 'róg_pocztowy',
 '📰': 'gazeta',
 '📱': 'telefon_komórkowy',
 '📲': 'telefon_komórkowy_ze_strzałką',
 '📳': 'tryb_wibracji',
 '📴': 'telefon_komórkowy_wyłączony',
 '📵': 'zakaz_używania_telefonów_komórkowych',
 '📶': 'siła_sygnału',
 '📷': 'aparat_fotograficzny',
 '📸': 'aparat_fotograficzny',
 '📹': 'kamera_wideo',
 '📺': 'telewizor',
 '📻': 'radio',
 '📼': 'kaseta_wideo',
 '📽': 'projektor_filmowy',
 '📿': 'różaniec',
 '🔀': 'przycisk_losowego_odtwarzania',
 '🔁': 'przycisk_powtarzania',
 '🔂': 'przycisk_powtórzenia',
 '🔃': 'strzałki',
 '🔄': 'strzałki',
 '🔅': 'przycisk_przyciemnienia',
 '🔆': 'przycisk_rozjaśnienia',
 '🔇': 'wyłączony_głośnik',
 '🔈': 'głośnik',
 '🔉': 'głośnik',
 '🔊': 'głośnik',
 '🔋': 'bateria',
 '🔌': 'wtyczka_elektryczna',
 '🔍': 'lupa',
 '🔎': 'lupa',
 '🔏': 'kłódka',
 '🔐': 'zamknięta',
 '🔑': 'klucz',
 '🔒': 'kłódka',
 '🔓': 'otwarta_kłódka',
 '🔔': 'dzwonek',
 '🔕': 'przekreślony_dzwonek',
 '🔖': 'zakładka',
 '🔗': 'ogniwo',
 '🔘': 'przycisk_radiowy',
 '🔙': 'strzałka_wstecz',
 '🔚': 'strzałka_koniec',
 '🔛': 'strzałka_włączone',
 '🔜': 'strzałka_wkrótce',
 '🔝': 'strzałka_do_góry',
 '🔞': 'zakaz_do_lat_18',
 '🔟': 'klawisz:_10',
 '🔠': 'litery',
 '🔡': 'litery',
 '🔢': 'cyfry',
 '🔣': 'symbole',
 '🔤': 'litery',
 '🔥': 'ogień',
 '🔦': 'latarka',
 '🔧': 'klucz_francuski',
 '🔨': 'młotek',
 '🔩': 'śruba_i_nakrętka',
 '🔪': 'nóż_kuchenny',
 '🔫': 'pistolet_na_wodę',
 '🔬': 'mikroskop',
 '🔭': 'teleskop',
 '🔮': 'kryształowa_kula',
 '🔯': 'gwiazda_dawida',
 '🔰': 'japoński_symbol_początkującego',
 '🔱': 'trójząb',
 '🔲': 'czarny_kwadratowy_przycisk',
 '🔳': 'biały_kwadratowy_przycisk',
 '🔴': 'czerwone_koło',
 '🔵': 'niebieskie_koło',
 '🔶': 'pomarańczowy_romb',
 '🔷': 'niebieski_romb',
 '🔸': 'pomarańczowy_romb',
 '🔹': 'niebieski_romb',
 '🔺': 'czerwony_trójkąt_w_górę',
 '🔻': 'czerwony_trójkąt_w_dół',
 '🔼': 'przycisk_w_górę',
 '🔽': 'przycisk_w_dół',
 '🕉': 'om',
 '🕊': 'gołąb',
 '🕋': 'kaaba',
 '🕌': 'meczet',
 '🕍': 'synagoga',
 '🕎': 'menora',
 '🕐': 'zegar',
 '🕑': 'zegar',
 '🕒': 'zegar',
 '🕓': 'zegar',
 '🕔': 'zegar',
 '🕕': 'zegar',
 '🕖': 'zegar',
 '🕗': 'zegar',
 '🕘': 'zegar',
 '🕙': 'zegar',
 '🕚': 'zegar',
 '🕛': 'zegar',
 '🕜': 'zegar',
 '🕝': 'zegar',
 '🕞': 'zegar',
 '🕟': 'zegar',
 '🕠': 'zegar',
 '🕡': 'zegar',
 '🕢': 'zegar',
 '🕣': 'zegar',
 '🕤': 'zegar',
 '🕥': 'zegar',
 '🕦': 'zegar',
 '🕧': 'zegar',
 '🕯': 'świeca',
 '🕰': 'zegar_kominkowy',
 '🕳': 'dziura',
 '🕴': 'mężczyzna_w_garniturze',
 '🕵': 'detektyw',
 '🕶': 'okulary_przeciwsłoneczne',
 '🕷': 'pająk',
 '🕸': 'pajęczyna',
 '🕹': 'joystick',
 '🕺': 'tańczący_mężczyzna',
 '🖇': 'spinacze',
 '🖊': 'długopis',
 '🖋': 'wieczne_pióro',
 '🖌': 'pędzel',
 '🖍': 'kredka',
 '🖐': 'machanie',
 '🖕': 'środkowy_palec',
 '🖖': 'salut_vulcan',
 '🖤': 'czarne_serce',
 '🖥': 'komputer_stacjonarny',
 '🖨': 'drukarka',
 '🖱': 'mysz_komputerowa',
 '🖲': 'trackball',
 '🖼': 'obrazek_w_ramce',
 '🗂': 'folder',
 '🗃': 'kartoteka',
 '🗄': 'szafka_na_dokumenty',
 '🗑': 'kosz_na_śmieci',
 '🗒': 'notes_spiralny',
 '🗓': 'kalendarz_spiralny',
 '🗜': 'zacisk',
 '🗝': 'klucz',
 '🗞': 'gazeta',
 '🗡': 'sztylet',
 '🗣': 'mówiąca_głowa',
 '🗨': 'dymek_mowy',
 '🗯': 'dymek_mowy',
 '🗳': 'urna_z_kartą_do_głosowania',
 '🗺': 'mapa_świata',
 '🗻': 'góra_fuji',
 '🗼': 'wieża_tokijska',
 '🗽': 'statua_wolności',
 '🗾': 'mapa_japonii',
 '🗿': 'moai',
 '😀': 'uśmiechnięta_twarz',
 '😁': 'szeroko_uśmiechnięta_twarz_z_uśmiechniętymi_oczami',
 '😂': 'twarz_ze_łzami_radości',
 '😃': 'uśmiechnięta_twarz_z_otwartymi_ustami',
 '😄': 'uśmiechnięta_twarz_z_otwartymi_ustami_i_uśmiechniętymi_oczami',
 '😅': 'uśmiechnięta_twarz_z_otwartymi_ustami_i_zimnym_potem',
 '😆': 'uśmiechnięta_twarz_z_otwartymi_ustami_i_mocno_zmrużonymi_oczami',
 '😇': 'uśmiechnięta_twarz_z_aureolą',
 '😈': 'uśmiechnięta_twarz_z_rogami',
 '😉': 'mrugająca_twarz',
 '😊': 'uśmiechnięta_twarz_z_uśmiechniętymi_oczami',
 '😋': 'twarz_oblizująca_się',
 '😌': 'twarz_z_wyrazem_ulgi',
 '😍': 'uśmiechnięta_twarz_z_oczami_w_kształcie_serca',
 '😎': 'uśmiechnięta_twarz_w_okularach_przeciwsłonecznych',
 '😏': 'twarz_z_uśmieszkiem',
 '😐': 'neutralna_twarz',
 '😑': 'twarz_bez_wyrazu',
 '😒': 'niezadowolona_twarz',
 '😓': 'twarz_z_zimnym_potem',
 '😔': 'zamyślona_twarz',
 '😕': 'zdezorientowana_twarz',
 '😖': 'zakłopotana_twarz',
 '😗': 'całująca_twarz',
 '😘': 'twarz_przesyłająca_pocałunek',
 '😙': 'całująca_twarz_z_uśmiechniętymi_oczami',
 '😚': 'całująca_twarz_z_zamkniętymi_oczami',
 '😛': 'twarz_pokazująca_język',
 '😜': 'twarz_pokazująca_język_i_mrugająca',
 '😝': 'twarz_pokazująca_język_i_mocno_zmrużone_oczy',
 '😞': 'rozczarowana_twarz',
 '😟': 'zmartwiona_twarz',
 '😠': 'zła_twarz',
 '😡': 'nadąsana_twarz',
 '😢': 'płacząca_twarz',
 '😣': 'wytrwała_twarz',
 '😤': 'twarz_z_parą_z_nosa',
 '😥': 'rozczarowana,_ale_odczuwająca_ulgę_twarz',
 '😦': 'zachmurzona_twarz_z_otwartymi_ustami',
 '😧': 'udręczona_twarz',
 '😨': 'przestraszona_twarz',
 '😩': 'zmęczona_twarz',
 '😪': 'senna_twarz',
 '😫': 'zmęczona_twarz',
 '😬': 'twarz_z_grymasem',
 '😭': 'głośno_płacząca_twarz',
 '😮': 'twarz_z_otwartymi_ustami',
 '😯': 'zdumiona_twarz',
 '😰': 'twarz_z_otwartymi_ustami_i_zimnym_potem',
 '😱': 'krzycząca_twarz_ze_strachu',
 '😲': 'zaskoczona_twarz',
 '😳': 'zarumieniona_twarz',
 '😴': 'śpiąca_twarz',
 '😵': 'oszołomiona_twarz',
 '😶': 'twarz_bez_ust',
 '😷': 'twarz_w_masce_medycznej',
 '😸': 'szeroko_uśmiechnięty_kot_z_uśmiechniętymi_oczami',
 '😹': 'kot_ze_łzami_radości',
 '😺': 'uśmiechnięty_kot_z_otwartymi_ustami',
 '😻': 'uśmiechnięty_kot_z_oczami_w_kształcie_serca',
 '😼': 'kot_z_ironicznym_uśmiechem',
 '😽': 'całujący_kot_z_zamkniętymi_oczami',
 '😾': 'nadąsany_kot',
 '😿': 'płaczący_kot',
 '🙀': 'zmęczony_kot',
 '🙁': 'lekko_zachmurzona_twarz',
 '🙂': 'lekko_uśmiechnięta_twarz',
 '🙃': 'odwrócona_twarz',
 '🙄': 'twarz_z_przewróconymi_oczami',
 '🙅': 'gest_nie',
 '🙆': 'gest_ok',
 '🙇': 'głęboki_ukłon',
 '🙈': 'nie_widzę_zła',
 '🙉': 'nie_słyszę_zła',
 '🙊': 'nie_mówię_o_złu',
 '🙋': 'szczęśliwa_osoba_podnosząca_rękę',
 '🙌': 'uniesione_ręce',
 '🙍': 'marszcząca_brwi_osoba',
 '🙎': 'nadąsana_osoba',
 '🙏': 'złożone_dłonie',
 '🚀': 'rakieta',
 '🚁': 'helikopter',
 '🚂': 'lokomotywa',
 '🚃': 'wagon_kolejowy',
 '🚄': 'szybki_pociąg',
 '🚅': 'szybki_pociąg',
 '🚆': 'pociąg',
 '🚇': 'metro',
 '🚈': 'kolej_miejska',
 '🚉': 'stacja',
 '🚊': 'tramwaj',
 '🚋': 'wagon_tramwajowy'}


polish_stopwords = [
    'a', 'aby', 'ach', 'acz', 'aczkolwiek', 'aj', 'albo', 'ale', 'alez', 'ależ',
    'ani', 'az', 'aż', 'beda', 'bedzie', 'deda', 'będą',
    'bede', 'będę', 'będzie', 'bo', 'bowiem', 'by', 'byc', 'być', 'byl', 'byla',
    'byli', 'bylo', 'byly', 'był', 'była', 'było', 'były', 'bynajmniej', 'cala',
    'cali', 'caly', 'cała', 'cały', 'ci', 'cie', 'ciebie', 'cię', 'co', 'cokolwiek',
    'cos', 'coś', 'czasami', 'czasem', 'czemu', 'czy', 'czyli', 'daleko', 'dla',
    'dlaczego', 'dlatego', 'do', 'dokad', 'dokąd', 'duzo',
    'dużo', 'dwa', 'dwaj', 'dwie', 'dwoje', 'dzis', 'dzisiaj', 'dziś', 'gdy', 'gdyby',
    'gdyz', 'gdyż', 'gdzie', 'gdziekolwiek', 'gdzies', 'gdzieś', 'go', 'i', 'ich',
    'ile', 'im', 'inna', 'inne', 'inny', 'innych', 'iz', 'iż', 'ja', 'jak', 'jakas',
    'jakaś', 'jakby', 'jaki', 'jakichs', 'jakichś', 'jakie', 'jakis', 'jakiś', 'jakiz',
    'jakiż', 'jakkolwiek', 'jako', 'jakos', 'jakoś', 'ją', 'je', 'jeden', 'jedna',
    'jednak', 'jednakze', 'jednakże', 'jedno', 'jego', 'jej', 'jemu', 'jesli', 'jest',
    'jestem', 'jeśli', 'jezeli', 'jeżeli', 'kazdy', 'każdy',
    'kiedy', 'kilka', 'kims', 'kimś', 'kto', 'ktokolwiek', 'ktora', 'ktore', 'ktorego',
    'ktorej', 'ktory', 'ktorych', 'ktorym', 'ktorzy', 'ktos', 'ktoś', 'która', 'które',
    'którego', 'której', 'który', 'których', 'którym', 'którzy', 'ku', 'lat', 'lecz',
    'lub', 'ma', 'mają', 'mam', 'mi', 'miedzy', 'między', 'mimo', 'mna', 'mną',
    'mnie', 'moga', 'mogą', 'moi', 'moim', 'moj', 'moja', 'moje', 'moze',
    'mozna', 'może', 'można', 'mój', 'mu', 'musi', 'my', 'na', 'nad', 'nam',
    'nami', 'nas', 'nasi', 'nasz', 'nasza', 'nasze', 'naszego', 'naszych', 'natomiast',
    'natychmiast', 'nawet', 'nia', 'nią', 'nic', 'nich', 'niech', 'niego', 'niej',
    'niemu', 'nim', 'nimi', 'niz', 'niż', 'no', 'o', 'obok', 'od', 'około',
    'on', 'ona', 'one', 'oni', 'ono', 'oraz', 'oto', 'owszem', 'pan', 'pana', 'pani',
    'po', 'pod', 'podczas', 'pomimo', 'ponad', 'poniewaz', 'ponieważ', 'powinien',
    'powinna', 'powinni', 'powinno', 'poza', 'przeciez', 'przecież', 'przed',
    'przede', 'przedtem', 'przez', 'przy', 'roku', 'rowniez', 'również', 'sam', 'sama',
    'są', 'sie', 'się', 'skad', 'skąd', 'soba', 'sobą', 'sobie', 'sposob', 'sposób',
    'swoje', 'ta', 'taka', 'taki', 'takie', 'takze', 'także', 'tam', 'te',
    'tego', 'tej', 'ten', 'to', 'toba', 'tobą', 'tobie', 'totez',
    'toteż', 'totobą', 'trzeba', 'tu', 'tutaj', 'twoi', 'twoim', 'twoj', 'twoja',
    'twoje', 'twój', 'twym', 'ty', 'tych', 'tylko', 'tym', 'u', 'w', 'wam', 'wami',
    'was', 'wasz', 'wasza', 'wasze', 'we', 'według', 'wiele', 'wielu', 'więc',
    'wszyscy', 'wszystkich', 'wszystkie', 'wszystkim', 'wszystko',
    'wtedy', 'wy', 'z', 'za', 'zaden', 'zadna', 'zadne', 'zadnych', 'zapewne',
    'ze', 'zeby', 'zeznowu', 'zł', 'znow', 'został', 'żaden',
    'żadna', 'żadne', 'żadnych', 'że', 'żeby'
]


def replace_emoji(text: str) -> str:
    """
    Replaces emojis in a given text based on the emoji dictionary provided.

    Args:
        text (str): The input string containing emojis.
        emoji_dict (dict): A dictionary where keys are emojis and values are replacements.

    Returns:
        str: The text with emojis replaced.
    """
    for emoji, replacement in EMOJI_TO_POLISH.items():
        text = text.replace(emoji, f" {replacement}")
    return text

def preprocess_tweet(tweet):
    # Replace URLs, mentions, and hashtags with spaces
    tweet = re.sub(r'http\S+|www\S+|https\S+', ' ', tweet, flags=re.MULTILINE)
    tweet = re.sub(r'@\w+|#\w+', ' ', tweet)

    # Replace underscores with spaces
    tweet = re.sub(r'_', ' ', tweet)

    # Remove unwanted characters, keeping letters, numbers, and spaces
    tweet = re.sub(r'[^a-zA-ZĄąĆćĘęŁłŃńÓóŚśŹźŻż0-9\s]', ' ', tweet)

    # Remove extra spaces
    tweet = re.sub(r'\s+', ' ', tweet).strip()

    return tweet

def create_tokenize_function(tokenizer):
  def tokenize_function(examples):
    result = tokenizer(examples['text'], padding='max_length', truncation=True, max_length=128)
    result['labels'] = [int(label) for label in examples['label']] 
    return result
  return tokenize_function

def remove_stops(text):
    if isinstance(text, str):
        words = text.split()
        filtered_words = [word for word in words if word.lower() not in polish_stopwords]
        return ' '.join(filtered_words)
    return text


def lemmatize_text(text):
    doc = nlp(text)
    return " ".join([token.lemma_ for token in doc])

def analyze_sentiment(text,tokenizer,model):
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True, max_length=128)
    with torch.no_grad():
        outputs = model(**inputs)
    probabilities = torch.softmax(outputs.logits, dim=1)
    sentiment_id = torch.argmax(probabilities, dim=1).item()
    sentiment = ["Negative", "Neutral", "Positive"][sentiment_id]
    confidence = probabilities[0][sentiment_id].item()
    return sentiment, confidence

def balance_text_data(df, label_col='labels', text_col='text', random_state=42):
    """Balances dataset using mixed sampling strategies"""
    np.random.seed(random_state)
    label_counts = df[label_col].value_counts()
    target_size = int(np.mean(label_counts))
    balanced_dfs = []
    
    for label in label_counts.index:
        df_class = df[df[label_col] == label]
        if len(df_class) > target_size:
            # Undersample
            df_class = resample(df_class, replace=False, 
                              n_samples=target_size, 
                              random_state=random_state)
        elif len(df_class) < target_size:
            # Oversample with noise
            n_samples = target_size - len(df_class)
            samples_to_duplicate = min(n_samples, len(df_class))
            df_duplicated = resample(df_class, 
                                   replace=True,
                                   n_samples=samples_to_duplicate, 
                                   random_state=random_state)
            df_class = pd.concat([df_class, df_duplicated])
        balanced_dfs.append(df_class)
    
    return pd.concat(balanced_dfs).sample(frac=1, random_state=random_state)

def compute_metrics(eval_pred: EvalPrediction):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    
    return {
        "accuracy": accuracy_score(labels, predictions),
        "f1_macro": f1_score(labels, predictions, average="macro"),
        "f1_weighted": f1_score(labels, predictions, average="weighted"),
        "f1_0": f1_score(labels, predictions, average=None)[0],
        "f1_1": f1_score(labels, predictions, average=None)[1],
        "f1_2": f1_score(labels, predictions, average=None)[2],
    }